name: build
on:
  workflow_dispatch:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install

      - name: Build
        run: |
          mv ./.env.example.json ./.env.json
          npm run build